############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Call for Papers"
url = "papers/"
weight = 2

[[main]]
name = "Committee"
url = "committee/"
weight = 3

[[main]]
name = "Submission"
url = "submission/"
weight = 4

[[main]]
name = "Registration"
url = "registration/"
weight = 5

[[main]]
name = "Schedule"
url = "schedule/"
weight = 6

[[main]]
name = "Contact"
url = "contactus/"
weight = 7

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Submission"
url = "submission/"
weight = 2

[[footer]]
name = "Contact"
url = "contactus/"
weight = 3
